import React, { useState, useEffect } from 'react';
import { createPortal } from 'react-dom';

interface ShareCardProps {
  analysisId: string;
  filename: string;
  onClose: () => void;
}

export default function ShareCard({ analysisId, filename, onClose }: ShareCardProps) {
  const [linkCopied, setLinkCopied] = useState(false);
  const [qrCodeUrl, setQrCodeUrl] = useState<string | null>(null);

  const shareUrl = `${window.location.origin}/analysis/${analysisId}/`;

  useEffect(() => {
    // Generate QR code using a service
    const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl)}`;
    setQrCodeUrl(qrUrl);
  }, [shareUrl]);

  const copyShareLink = async () => {
    try {
      await navigator.clipboard.writeText(shareUrl);
      setLinkCopied(true);
      setTimeout(() => setLinkCopied(false), 2000);
    } catch (error) {
      console.error('Failed to copy link:', error);
    }
  };

  const shareViaEmail = () => {
    // 获取完整的分析数据以生成更详细的邮件内容
    const getCurrentAnalysisData = () => {
      // 尝试从全局变量获取
      if ((window as any).currentAnalysisResult) {
        return (window as any).currentAnalysisResult;
      }
      // 尝试从 sessionStorage 获取
      try {
        const stored = sessionStorage.getItem('heroAnalysisResult');
        if (stored) {
          return JSON.parse(stored);
        }
      } catch (e) {
        console.error('Failed to parse stored analysis result:', e);
      }
      return null;
    };

    const data = getCurrentAnalysisData();
    
    // 生成邮件主题和内容
    const getCleanFilename = (name: string) => {
      if (!name) return 'audio_file';
      return name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    };

    const cleanFilename = data ? getCleanFilename(data.filename) : getCleanFilename(filename);
    const subject = `Audio Analysis Results: ${data?.filename || filename}`;
    
    // 生成邮件正文
    let body = `I wanted to share comprehensive audio analysis results for "${data?.filename || filename}":\n\n`;
    body += `🔗 View the full analysis: ${shareUrl}\n\n`;
    
    if (data && data.basicInfo) {
      body += `📊 Key Insights:\n`;
      body += `• Genre: ${data.basicInfo.genre || 'Unknown'}\n`;
      body += `• BPM: ${data.basicInfo.bpm || 'N/A'}\n`;
      body += `• Mood: ${data.basicInfo.mood || 'Unknown'}\n`;
      if (data.quality?.overall) {
        body += `• Quality Score: ${data.quality.overall}/10\n`;
      }
      body += `\n`;
    }
    
    body += `Check out the detailed analysis with AI-powered insights, emotion detection, and more!\n\n`;
    body += `---\n`;
    body += `Generated by Describe Music - AI-Powered Audio Analysis`;
    
    // 使用 Gmail 网页版链接（更可靠）
    const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(gmailUrl, '_blank', 'width=800,height=600');
    
    // 备选方案：也尝试打开 mailto（如果用户有配置邮件客户端）
    // 延迟执行，避免被浏览器阻止
    setTimeout(() => {
      const mailto = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
      // 创建一个隐藏的链接并点击它
      const link = document.createElement('a');
      link.href = mailto;
      link.style.display = 'none';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }, 100);
  };

  const shareToTwitter = () => {
    // 获取完整的分析数据（与导航栏分享功能保持一致）
    const getCurrentAnalysisData = () => {
      // 尝试从全局变量获取
      if ((window as any).currentAnalysisResult) {
        return (window as any).currentAnalysisResult;
      }
      // 尝试从 sessionStorage 获取
      try {
        const stored = sessionStorage.getItem('heroAnalysisResult');
        if (stored) {
          return JSON.parse(stored);
        }
      } catch (e) {
        console.error('Failed to parse stored analysis result:', e);
      }
      return null;
    };

    const data = getCurrentAnalysisData();
    
    // 生成更有吸引力的 Twitter 文案（与导航栏保持一致）
    // Twitter 会自动在推文末尾添加链接，所以文案中不需要包含链接提示
    const getCleanFilename = (name: string) => {
      if (!name) return 'audio_file';
      return name.replace(/[^a-z0-9]/gi, '_').toLowerCase();
    };

    const cleanFilename = data ? getCleanFilename(data.filename) : getCleanFilename(filename);
    
    let text = `🎵 Just analyzed "${data?.filename || filename}" with AI-powered audio analysis!\n\n`;
    
    if (data && data.basicInfo) {
      text += `🎯 ${data.basicInfo.genre || 'Music'} • ${data.basicInfo.bpm || 'N/A'} BPM • ${data.basicInfo.mood || 'Unknown'} mood`;
      if (data.quality?.overall) {
        text += ` • ⭐ ${data.quality.overall}/10`;
      }
      text += `\n\n`;
    } else {
      text += `Discover detailed insights about genre, mood, BPM, and more!\n\n`;
    }
    
    text += `#AudioAnalysis #AIMusic #MusicTech #DescribeMusic`;
    
    // Twitter 字符限制是 280，链接会占用约 23 字符，所以文案限制在 250 字符内
    const maxLength = 250;
    if (text.length > maxLength) {
      // 简化版本：只保留核心信息
      if (data && data.basicInfo) {
        text = `🎵 Just analyzed "${data.filename || filename}" with AI!\n\n`;
        text += `🎯 ${data.basicInfo.genre || 'Music'} • ${data.basicInfo.bpm || 'N/A'} BPM • ${data.basicInfo.mood || 'Unknown'}\n\n`;
        text += `#AudioAnalysis #AIMusic #MusicTech`;
      } else {
        text = `🎵 Just analyzed "${filename}" with AI-powered audio analysis!\n\n`;
        text += `#AudioAnalysis #AIMusic #MusicTech`;
      }
    }
    
    const url = `https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(shareUrl)}`;
    window.open(url, '_blank', 'width=550,height=420');
  };

  const shareToLinkedIn = () => {
    // 获取完整的分析数据
    const getCurrentAnalysisData = () => {
      if ((window as any).currentAnalysisResult) {
        return (window as any).currentAnalysisResult;
      }
      try {
        const stored = sessionStorage.getItem('heroAnalysisResult');
        if (stored) {
          return JSON.parse(stored);
        }
      } catch (e) {
        console.error('Failed to parse stored analysis result:', e);
      }
      return null;
    };

    const data = getCurrentAnalysisData();
    const summary = data && data.basicInfo 
      ? `Just analyzed "${data.filename || filename}" with AI-powered audio analysis! Genre: ${data.basicInfo.genre || 'Music'}, BPM: ${data.basicInfo.bpm || 'N/A'}, Mood: ${data.basicInfo.mood || 'Unknown'}`
      : `Check out this AI-powered audio analysis: ${filename}`;
    const url = `https://www.linkedin.com/sharing/share-offsite/?url=${encodeURIComponent(shareUrl)}&summary=${encodeURIComponent(summary)}`;
    window.open(url, '_blank', 'width=550,height=420');
  };

  const shareToFacebook = () => {
    const url = `https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(shareUrl)}`;
    window.open(url, '_blank', 'width=550,height=420');
  };

  // 获取完整分析数据的辅助函数
  const getCurrentAnalysisData = () => {
    if ((window as any).currentAnalysisResult) {
      return (window as any).currentAnalysisResult;
    }
    try {
      const stored = sessionStorage.getItem('heroAnalysisResult');
      if (stored) {
        return JSON.parse(stored);
      }
    } catch (e) {
      console.error('Failed to parse stored analysis result:', e);
    }
    return null;
  };

  const shareToReddit = () => {
    const data = getCurrentAnalysisData();
    const title = data && data.filename 
      ? `AI-Powered Audio Analysis: ${data.filename} - ${data.basicInfo?.genre || 'Music'} | ${data.basicInfo?.bpm || 'N/A'} BPM`
      : `AI-Powered Audio Analysis: ${filename}`;
    const url = `https://www.reddit.com/submit?url=${encodeURIComponent(shareUrl)}&title=${encodeURIComponent(title)}`;
    window.open(url, '_blank', 'width=550,height=420');
  };

  const shareToWhatsApp = () => {
    const data = getCurrentAnalysisData();
    let text = `🎵 Check out this AI-powered audio analysis!\n\n`;
    if (data && data.basicInfo) {
      text += `🎯 ${data.basicInfo.genre || 'Music'} • ${data.basicInfo.bpm || 'N/A'} BPM • ${data.basicInfo.mood || 'Unknown'} mood\n\n`;
    }
    text += `🔗 ${shareUrl}`;
    const url = `https://wa.me/?text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const shareToTelegram = () => {
    const data = getCurrentAnalysisData();
    let text = `🎵 Check out this AI-powered audio analysis!\n\n`;
    if (data && data.basicInfo) {
      text += `🎯 ${data.basicInfo.genre || 'Music'} • ${data.basicInfo.bpm || 'N/A'} BPM • ${data.basicInfo.mood || 'Unknown'} mood\n\n`;
    }
    text += `🔗 ${shareUrl}`;
    const url = `https://t.me/share/url?url=${encodeURIComponent(shareUrl)}&text=${encodeURIComponent(text)}`;
    window.open(url, '_blank');
  };

  const shareToPinterest = () => {
    const description = `AI-Powered Audio Analysis: ${filename}`;
    const url = `https://pinterest.com/pin/create/button/?url=${encodeURIComponent(shareUrl)}&description=${encodeURIComponent(description)}`;
    window.open(url, '_blank', 'width=550,height=420');
  };


  const modalContent = (
    <div 
      className="fixed top-0 left-0 right-0 bottom-0 z-[100] flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm" 
      style={{ 
        width: '100vw', 
        height: '100vh',
        minWidth: '100vw',
        minHeight: '100vh',
        position: 'fixed',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        margin: 0,
        padding: '1rem'
      }}
    >
      <div className="relative w-full max-w-md glass-pane p-6 rounded-xl border border-white/10 shadow-2xl animate-in fade-in zoom-in-95 duration-300 z-[101]">
        {/* Close button */}
        <button
          onClick={onClose}
          className="absolute top-4 right-4 p-2 text-slate-400 hover:text-white rounded-lg hover:bg-white/5 transition-all duration-200"
        >
          <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>

        {/* Header */}
        <div className="mb-6">
          <h3 className="text-xl font-bold text-white mb-2 flex items-center gap-2">
            <svg className="w-5 h-5 text-violet-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8.684 13.342C8.886 12.938 9 12.482 9 12c0-.482-.114-.938-.316-1.342m0 2.684a3 3 0 110-2.684m0 2.684l6.632 3.316m-6.632-6l6.632-3.316m0 0a3 3 0 105.367-2.684 3 3 0 00-5.367 2.684zm0 9.316a3 3 0 105.367 2.684 3 3 0 00-5.367-2.684z" />
            </svg>
            Share Analysis
          </h3>
          <p className="text-sm text-slate-400">Share this analysis with others</p>
        </div>

        {/* Share Link Section */}
        <div className="mb-6">
          <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
            Share Link
          </label>
          <div className="flex items-center gap-2">
            <input
              type="text"
              value={shareUrl}
              readOnly
              className="flex-1 px-3 py-2 bg-slate-800/50 border border-slate-700 rounded-lg text-sm text-slate-300 font-mono truncate"
            />
            <button
              onClick={copyShareLink}
              className={`px-4 py-2 rounded-lg font-medium text-sm transition-all duration-200 ${
                linkCopied
                  ? 'bg-green-500/20 text-green-400 border border-green-500/30'
                  : 'bg-gradient-to-r from-violet-500 to-blue-500 text-white hover:from-violet-600 hover:to-blue-600'
              }`}
            >
              {linkCopied ? (
                <span className="flex items-center gap-2">
                  <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                  </svg>
                  Copied!
                </span>
              ) : (
                'Copy'
              )}
            </button>
          </div>
        </div>

        {/* QR Code Section */}
        {qrCodeUrl && (
          <div className="mb-6 text-center">
            <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-2">
              QR Code
            </label>
            <div className="inline-block p-3 bg-white rounded-lg">
              <img src={qrCodeUrl} alt="QR Code" className="w-32 h-32" />
            </div>
            <p className="text-xs text-slate-500 mt-2">Scan to open on mobile</p>
          </div>
        )}

        {/* Social Media Buttons */}
        <div>
          <label className="block text-xs font-semibold text-slate-400 uppercase tracking-wider mb-3">
            Share on Social Media
          </label>
          <div className="grid grid-cols-2 gap-3">
            <button
              onClick={shareViaEmail}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-blue-500/20 border border-slate-700 hover:border-blue-500/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-blue-400 group-hover:text-blue-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Email</span>
            </button>
            <button
              onClick={shareToTwitter}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-sky-500/20 border border-slate-700 hover:border-sky-500/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-sky-400" fill="currentColor" viewBox="0 0 24 24">
                <path d="M23 3a10.9 10.9 0 01-3.14 1.53 4.48 4.48 0 00-7.86 3v1A10.66 10.66 0 013 4s-4 9 5 13a11.64 11.64 0 01-7 2c9 5 20 0 20-11.5a4.5 4.5 0 00-.08-.83A7.72 7.72 0 0023 3z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Twitter</span>
            </button>
            <button
              onClick={shareToFacebook}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-blue-600/20 border border-slate-700 hover:border-blue-600/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-blue-600" fill="currentColor" viewBox="0 0 24 24">
                <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Facebook</span>
            </button>
            <button
              onClick={shareToLinkedIn}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-blue-700/20 border border-slate-700 hover:border-blue-700/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-blue-500" fill="currentColor" viewBox="0 0 24 24">
                <path d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">LinkedIn</span>
            </button>
            <button
              onClick={shareToReddit}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-orange-500/20 border border-slate-700 hover:border-orange-500/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-orange-500" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0zm5.01 4.744c.688 0 1.25.561 1.25 1.249a1.25 1.25 0 0 1-2.498.056l-2.597-.547-.8 3.747c1.824.07 3.48.632 4.674 1.488.308-.309.73-.491 1.207-.491.968 0 1.754.786 1.754 1.754 0 .716-.435 1.333-1.01 1.614a3.111 3.111 0 0 1 .042.52c0 2.694-3.13 4.87-7.004 4.87-3.874 0-7.004-2.176-7.004-4.87 0-.183.015-.366.043-.534A1.748 1.748 0 0 1 4.028 12c0-.968.786-1.754 1.754-1.754.463 0 .898.196 1.207.49 1.207-.883 2.878-1.43 4.744-1.487l.885-4.182a.342.342 0 0 1 .14-.197.35.35 0 0 1 .238-.042l2.906.617a1.214 1.214 0 0 1 1.108-.701zM9.25 12C8.561 12 8 12.562 8 13.25c0 .687.561 1.248 1.25 1.248.687 0 1.248-.561 1.248-1.249 0-.688-.561-1.249-1.249-1.249zm5.5 0c-.687 0-1.248.561-1.248 1.25 0 .687.561 1.248 1.249 1.248.688 0 1.249-.561 1.249-1.249 0-.687-.562-1.249-1.25-1.249zm-5.466 3.99a.327.327 0 0 0-.231.094.33.33 0 0 0 0 .463c.842.842 2.484.913 2.961.913.477 0 2.105-.056 2.961-.913a.361.361 0 0 0 .029-.463.33.33 0 0 0-.464 0c-.547.533-1.684.73-2.512.73-.828 0-1.979-.196-2.512-.73a.326.326 0 0 0-.232-.095z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Reddit</span>
            </button>
            <button
              onClick={shareToWhatsApp}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-green-500/20 border border-slate-700 hover:border-green-500/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-green-500" fill="currentColor" viewBox="0 0 24 24">
                <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893a11.821 11.821 0 00-3.48-8.413Z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">WhatsApp</span>
            </button>
            <button
              onClick={shareToTelegram}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-blue-400/20 border border-slate-700 hover:border-blue-400/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-blue-400" fill="currentColor" viewBox="0 0 24 24">
                <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.559z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Telegram</span>
            </button>
            <button
              onClick={shareToPinterest}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-slate-800/50 hover:bg-red-600/20 border border-slate-700 hover:border-red-600/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-red-600" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.174-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.169 1.775 2.169 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.75-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12.017 24c6.624 0 11.99-5.367 11.99-11.987C24.007 5.367 18.641.001 12.017.001z"/>
              </svg>
              <span className="text-sm text-slate-300 group-hover:text-white">Pinterest</span>
            </button>
            <button
              onClick={copyShareLink}
              className="flex items-center justify-center gap-2 px-4 py-3 bg-gradient-to-r from-violet-500/20 to-blue-500/20 hover:from-violet-500/30 hover:to-blue-500/30 border border-violet-500/30 rounded-lg transition-all duration-200 group"
            >
              <svg className="w-5 h-5 text-violet-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.828 10.172a4 4 0 00-5.656 0l-4 4a4 4 0 105.656 5.656l1.102-1.101m-.758-4.899a4 4 0 005.656 0l4-4a4 4 0 00-5.656-5.656l-1.1 1.1" />
              </svg>
              <span className="text-sm text-white">Copy Link</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );

  return createPortal(modalContent, document.body);
}

